name: Semantic Release

on:
  push:
    branches:
      - main
      - next

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # required for semantic-release to push changes

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org' # Optional: if you want to publish to npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Token for npm publish
          # NPM_TOKEN is an alias for NODE_AUTH_TOKEN and is also supported
